require 'optparse'
require 'ruby-progressbar'

require 'git_sentiment/version'
require 'git_sentiment/git'
require 'git_sentiment/word_finder'
require 'git_sentiment/format'
require 'git_sentiment/formats/csv'
require 'git_sentiment/formats/html'
require 'git_sentiment/options'
require 'git_sentiment/cli'
